name: tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh
      - name: Run Ollama
        run: ollama pull "qwen2.5-coder:1.5b" && ollama serve & sleep 5    # wait for the Ollama server to be ready
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
